オブジェクト指向の活用

《サンプルコード》

In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler0 = StandardScaler()
scaler1 = StandardScaler()
scaler2 = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


【問題1】これまで利用してきたクラスの列挙

クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

[pandas]
  DataFrame
  Series

[matplotlib]
  Figure
  Axes

[scikit-learn]
  LogisticRegression
  KNeighborsClassifier

【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

メソッド

mean()
min()
max()
rename()
seed()

インスタンス変数

T
value
shape
fig
scaler

【問題3】標準化クラスをスクラッチで作成

理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

In [12]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        #配列の列平均を求めて代入する
        self.mean_ = np.mean(X,axis=0)
        #配列の列の分散を求める
        self.var_ = np.var(X,axis=0)
        pass
    
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        #標準化する
        mu = self.mean_             #平均値
        sigma = np.std(X,axis=0)    #標準偏差
        X_scaled = (X - mu)/ sigma  #標準化する式
        pass
        return X_scaled

以下のコードが実行できるようにしましょう。

In [13]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


【問題4】 四則演算を行うクラスの作成

ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [37]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):   #コンストラクタ 
        self.value = value
        try:
            if value <= 0 or value > 0:
                print("初期値{}が設定されました".format(self.value))       
        except TypeError:
            print("ERROR")
            
    #足し算のメソッド    
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
    #引き算のメソッド
    def sub(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value3
    #掛け算のメソッド
    def mul(self, value4):
        """
        受け取った引数をself.valueにかける掛ける
        """
        self.value *= value4
    #割り算のメソッド
    def div(self, value5):
        """
        受け取った引数をself.valueで割る
        """
        self.value /= value5
        
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example = ExampleClass(5)
example.sub(3)
print("value : {}".format(example.value))
example = ExampleClass(5)
example.mul(3)
print("value : {}".format(example.value))
example = ExampleClass(5)
example.div(3)
print("value : {}".format(example.value))
example = ExampleClass("hello")

初期値5が設定されました
value : 5
value : 8
初期値5が設定されました
value : 2
初期値5が設定されました
value : 15
初期値5が設定されました
value : 1.6666666666666667
ERROR
